//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _4_0_4_25d_bms {
            get {
                object obj = ResourceManager.GetObject("4_0.4.25d.bms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _4_0_4_27d_bms {
            get {
                object obj = ResourceManager.GetObject("4_0.4.27d.bms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coreKeeper_logo {
            get {
                object obj = ResourceManager.GetObject("coreKeeper_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DaDlogo {
            get {
                object obj = ResourceManager.GetObject("DaDlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap escapesim_logo {
            get {
                object obj = ResourceManager.GetObject("escapesim_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///color a
        ///for %%a in (*.unity3D;*.bundle) do UPacker.exe exportbundle &quot;%%a&quot;.
        /// </summary>
        internal static string Export_bundles_bat {
            get {
                return ResourceManager.GetString("Export_bundles.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///for %%a in (resources.assets;) do UPacker.exe export &quot;%%a&quot; -mb_new -t LanguageSourceAsset
        ///.
        /// </summary>
        internal static string Export_l2_bat {
            get {
                return ResourceManager.GetString("Export_l2.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на quickbms_files.exe 4_0.4.27d.bms pakchunk0-WindowsNoEditor.pak pakchunk0-WindowsNoEditor.
        /// </summary>
        internal static string export_locres_bat {
            get {
                return ResourceManager.GetString("export_locres.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///for %%a in (sharedassets0.assets;) do UPacker.exe export &quot;%%a&quot; -mb_new -t ttf
        ///.
        /// </summary>
        internal static string Export_ttf_bat {
            get {
                return ResourceManager.GetString("Export_ttf.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///color a
        ///for %%a in (resources.assets;) do UPacker_Advanced.exe export &quot;%%a&quot; -t txt.
        /// </summary>
        internal static string Export_txt_bat {
            get {
                return ResourceManager.GetString("Export_txt.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UE4localizationsTool.exe export Game.locres.
        /// </summary>
        internal static string export_txt_from_locres_bat {
            get {
                return ResourceManager.GetString("export_txt_from_locres.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///for %%a in (*.LanguageSource;*.LanguageSourceAsset;) do Parser_ULS.exe -e &quot;%%a&quot; -o $0c -dauto -ndesc
        ///.
        /// </summary>
        internal static string export_uls_bat {
            get {
                return ResourceManager.GetString("export_uls.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] geckodriver_exe {
            get {
                object obj = ResourceManager.GetObject("geckodriver.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///color a
        ///for %%a in (*.assets;) do UPacker_Advanced.exe import &quot;%%a&quot; -mb_new.
        /// </summary>
        internal static string Import_ALL_MBnew_bat {
            get {
                return ResourceManager.GetString("Import_ALL_MBnew.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///for %%a in (sharedassets0.assets;) do UPacker.exe import &quot;%%a&quot; -mb_new -t font_raw.
        /// </summary>
        internal static string Import_Fonts_bat {
            get {
                return ResourceManager.GetString("Import_Fonts.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///for %%a in (resources.assets;) do UPacker.exe import &quot;%%a&quot; -mb_new -t 114
        ///.
        /// </summary>
        internal static string Import_l2_bat {
            get {
                return ResourceManager.GetString("Import_l2.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///color a
        ///for %%a in (*.assets;) do UPacker_Advanced.exe import &quot;%%a&quot; -t tex.
        /// </summary>
        internal static string Import_textures_bat {
            get {
                return ResourceManager.GetString("Import_textures.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///color a
        ///for %%a in (resources.assets;) do UPacker_Advanced.exe import &quot;%%a&quot; -t txt.
        /// </summary>
        internal static string Import_txt_bat {
            get {
                return ResourceManager.GetString("Import_txt.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UE4localizationsTool.exe import Game.locres.txt Game.locres.
        /// </summary>
        internal static string import_txt_into_locres_bat {
            get {
                return ResourceManager.GetString("import_txt_into_locres.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на u4pak.exe test.u4pak.
        /// </summary>
        internal static string import_u4pak_bat {
            get {
                return ResourceManager.GetString("import_u4pak.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///for %%a in (*.LanguageSource;*.LanguageSourceAsset;) do Parser_ULS.exe -i &quot;%%a&quot; -o $0c -dauto
        ///.
        /// </summary>
        internal static string import_uls_bat {
            get {
                return ResourceManager.GetString("import_uls.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mortuary_logo {
            get {
                object obj = ResourceManager.GetObject("mortuary_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] nw_oodle_bms {
            get {
                object obj = ResourceManager.GetObject("nw_oodle.bms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///for %%a in (*.csv) do unPacker_CSV.exe -pc 4 &quot;%%a&quot;
        ///.
        /// </summary>
        internal static string pack_CX_bat {
            get {
                return ResourceManager.GetString("pack_CX.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Parser_ULS_exe {
            get {
                object obj = ResourceManager.GetObject("Parser_ULS.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] quickbms_4gb_files_exe {
            get {
                object obj = ResourceManager.GetObject("quickbms_4gb_files.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] quickbms_exe {
            get {
                object obj = ResourceManager.GetObject("quickbms.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] show_exe {
            get {
                object obj = ResourceManager.GetObject("show.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap temtemLogo {
            get {
                object obj = ResourceManager.GetObject("temtemLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] test_u4pak {
            get {
                object obj = ResourceManager.GetObject("test.u4pak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] u4pak_exe {
            get {
                object obj = ResourceManager.GetObject("u4pak.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] UE4localizationsTool_exe {
            get {
                object obj = ResourceManager.GetObject("UE4localizationsTool.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @echo off
        ///for %%a in (*.csv) do unPacker_CSV.exe -uc 4 &quot;%%a&quot;
        ///.
        /// </summary>
        internal static string unpack_CX_bat {
            get {
                return ResourceManager.GetString("unpack_CX.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] unPacker_CSV_exe {
            get {
                object obj = ResourceManager.GetObject("unPacker_CSV.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] UPacker_Advanced_exe {
            get {
                object obj = ResourceManager.GetObject("UPacker_Advanced.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] UPacker_exe {
            get {
                object obj = ResourceManager.GetObject("UPacker.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap utranslate_updater {
            get {
                object obj = ResourceManager.GetObject("utranslate_updater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon utranslator {
            get {
                object obj = ResourceManager.GetObject("utranslator", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap utranslatorico {
            get {
                object obj = ResourceManager.GetObject("utranslatorico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vk {
            get {
                object obj = ResourceManager.GetObject("vk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на quickbms.exe -k -f *.loc.xml nw_oodle.bms DataStrm-part1.pak levels\newlevels.
        /// </summary>
        internal static string xml_q_export_bat {
            get {
                return ResourceManager.GetString("xml_q_export.bat", resourceCulture);
            }
        }
    }
}
